<a href="https://colab.research.google.com/github/Vinayak-Sharma12/Working_with_Numpy_with_me/blob/main/Working_with_Numpy_with_me.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **NUMPY**
*Numpy library is specially designed for the Array*

Difference in Array and List is that array stores same data type whereas list you know can store any data type

In [1]:
import numpy as np

-->Converting List into Array

In [2]:
 my_list=[1,2,3,4,5]
 arr=np.array(my_list)
 print(arr)
 type(arr)
 #print(my_list)

[1 2 3 4 5]


numpy.ndarray

In [17]:
## Multinested array
my_lst1=[1,2,3]
my_lst2=[2,3,4]
my_lst3=[9,7,6]

arr=np.array([my_lst1,my_lst2,my_lst3])
print(arr)
type(arr)

[[1 2 3]
 [2 3 4]
 [9 7 6]]


numpy.ndarray

In [18]:
#Check the shape of the array
# Shape - Rows and Column
arr.shape

(3, 3)

# Indexing

In [21]:
L=[1,2,3,4,5,6]
arrie=np.array(L)
arrie


array([1, 2, 3, 4, 5, 6])

In [23]:
arrie[3]

4

In [41]:
#Updating element in the array
arrie[3:]=100
arrie

array([  1,   2,   3, 100, 100, 100])

In [38]:
#Accessing elemnent of multinested
arr[0:1,2:3]

array([[3]])

In [ ]:
arr

array([[1, 2, 3],
       [2, 3, 4],
       [9, 7, 6]])

In [39]:
arr[0:2,1:3]

array([[2, 3],
       [3, 4]])

## Some Conditions very Useful in Data Analysis

In [44]:
# Using A Filter for us
# 1-D Array
value=3
result=arrie[arrie<value]
result

array([1, 2])

In [45]:
#2-D Array
value=4
answer=arr[arr<value]
answer

array([1, 2, 3, 2, 3])

In [53]:
# Creating and Reshaping an array
arr1= np.arange(0,10).reshape(2,5)
arr2=np.arange(0,10).reshape(5,2)
print(arr1)
print(" ")
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [56]:
# Multiplication of array can only be done with array of same shape
arr1*arr1

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [59]:
# Creating an array with 1
arr3=np.ones((2,4),dtype=int)
arr3

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [60]:
#Creating an array with random number
np.random.rand(3,3)

array([[0.50905381, 0.72023678, 0.41185804],
       [0.74708835, 0.34496569, 0.79129902],
       [0.06486513, 0.47278877, 0.26192317]])

In [62]:
#Creating an array with Standard Normal  Distribution
np.random.randn(4,4)

array([[-0.57818635, -0.70333159, -1.17140771, -0.28403588],
       [-0.11391703,  1.32342445, -1.40588352,  0.44437344],
       [ 0.35874307, -0.39663827,  0.06606212,  2.05503069],
       [ 0.28625195,  0.11310301, -0.01846355,  0.07741415]])